### ISSUE TITLE
Make base image a Jinja variable.

### ISSUE THREAD

**Issue by jinyangustc** [athackst/dockerfiles#185]
Hi Allison, thank you for your blog posts on ROS2 + VSCode, the template repo and this repo. As someone just getting started with ROS, I found them extremely helpful.

My research project needs an environment with both ROS2 and CUDA. But currently the template hardcoded base image as `ubuntu` and it looks like CUDA and its dependencies are not installed. I'm thinking about changing the base image from
```
FROM ubuntu:{{ ubuntu_distro }} AS base
```
to something like:
```
FROM {{ base_image }}:{{ image_version }} AS base
```
so that in the template file we could write
```
...
ros2:
  -
    name: galactic
    ros_distro: galactic
    targets:
      - base
      - dev
      - full
      - gazebo
      - gazebo-nvidia
    python_version: "3.8"
    base_image: "nvidia/cuda"
    image_version: "11.0.3-runtime-ubuntu20.04"
...
```
I don't know if this is a use case you want to support, but I can try submitting a PR if you're interested. If not, that's pretty understandable and I'm happy to maintain my own fork.

Thank you again for your great work!
